networks:
  default:
    name: medallion_network

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    entrypoint: >
      /bin/sh -c " minio server /lake --console-address ':9001' & sleep 5; mc alias set local http://localhost:9000 admin password; mc mb --ignore-existing local/bronze; mc mb --ignore-existing local/silver; mc mb --ignore-existing local/gold; echo 'Buckets created successfully'; wait "
    volumes:
      - minio_data:/lake

  # --- Metadata & Audit Store (Postgres) ---
  logging_db:
    image: postgres:17.9
    container_name: logging_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres # Create this database automatically on startup and then run all initialization scripts inside it.
    ports:
      - "5432:5432"
    volumes:
      - ./warehouse/init_multiple_dbs.sql:/docker-entrypoint-initdb.d/init_multiple_dbs.sql:ro
      - metadata_postgres_data:/var/lib/postgresql/data

  source-db:
    image: postgres:17.9
    container_name: source-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: production_db
    ports:
      - "5433:5432"
    volumes:
      - source_postgres_data:/var/lib/postgresql/data

  spark-master:
    image: apache/spark:4.0.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/credentials.json
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./raw:/raw:ro
      - ./spark/extra_jars:/opt/spark/extra_jars
      - ./application_default_credentials.json:/opt/spark/credentials.json:ro
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:4.0.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/credentials.json
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./raw:/raw:ro
      - ./spark/extra_jars:/opt/spark/extra_jars
      - ./application_default_credentials.json:/opt/spark/credentials.json:ro
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow
    depends_on:
      - logging_db
      - minio
      - source-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@logging_db/airflow_db
      - SPARK_HOME=/opt/spark
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_CREATE=true
      - AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER=True
      - AIRFLOW_UID=502
      - PYTHONWARNINGS=ignore
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/credentials.json
      - AIRFLOW_VAR_DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - AIRFLOW_VAR_GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - AIRFLOW_VAR_BQ_DATASET=${BQ_DATASET}
      - AIRFLOW_VAR_BQ_TEMP_BUCKET=${BQ_TEMP_BUCKET}
    ports:
      - "8088:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./raw:/raw:ro
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/extra_jars:/opt/spark/extra_jars
      - ./application_default_credentials.json:/opt/spark/credentials.json:ro
    command: >
      bash -c " airflow db migrate && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin || true; airflow scheduler & exec airflow webserver"

volumes:
  metadata_postgres_data:
  minio_data:
  source_postgres_data:
